import Image from "next/image";
import { projects } from "../src/data/projects";

const github = "https://github.com/vietanh1109a";
const upwork = "https://www.upwork.com/freelancers/~015f59105dfd2e6d25";
const services = [["Python Automation", "Scripts and utilities for repetitive workflows, file processing, and manual business tasks."], ["CSV & Excel Processing", "Cleaning, merging, transforming, validating, analyzing, and reporting spreadsheet data."], ["API Integration", "REST API integrations, webhooks, API-to-file workflows, and structured data processing."], ["Web Scraping", "Public web data extraction using HTTP and browser automation with structured CSV/Excel outputs."], ["Backend Utilities", "Practical FastAPI and Flask tools for data, automation, and API workflows."], ["Existing Python Script Improvements", "Fixing, extending, testing, and improving existing small Python tools."]];
const stack = { Core: ["Python", "SQL", "JSON"], Data: ["pandas", "Microsoft Excel", "openpyxl"], "Backend & APIs": ["FastAPI", "Flask", "REST APIs", "API Integration"], Scraping: ["httpx", "BeautifulSoup", "Playwright"], Database: ["PostgreSQL", "SQLite", "SQLAlchemy"], Testing: ["pytest"] };
function Arrow() { return <span aria-hidden="true">↗</span>; }

export default function Home() { return <main>
  <header className="site-header"><a className="brand" href="#top" aria-label="Anh N. home">Anh N.<i /></a><nav className="desktop-nav" aria-label="Main navigation"><a href="#services">Services</a><a href="#projects">Projects</a><a href="#stack">Stack</a><a href="#about">About</a><a href="#contact">Contact</a></nav><a className="github-link" href={github} target="_blank" rel="noreferrer">GitHub <Arrow /></a><details className="mobile-nav"><summary aria-label="Open navigation">Menu</summary><nav aria-label="Mobile navigation"><a href="#services">Services</a><a href="#projects">Projects</a><a href="#stack">Stack</a><a href="#about">About</a><a href="#contact">Contact</a><a href={github}>GitHub</a></nav></details></header>
  <section className="hero wrap" id="top"><p className="eyebrow">Anh N. · Hanoi, Vietnam</p><h1>Python<br /><em>Developer</em></h1><p className="hero-title">Automation, APIs, Data Processing &amp; Web Scraping</p><p className="lead">I help businesses automate repetitive work, process data, connect APIs, and build practical Python tools.</p><div className="availability"><span>Available 30+ hrs/week</span><span>$10/hr</span></div><div className="actions"><a className="button primary" href="#projects">View Projects <Arrow /></a><a className="button" href={github} target="_blank" rel="noreferrer">GitHub <Arrow /></a><a className="text-link" href={upwork} target="_blank" rel="noreferrer">Upwork Profile <Arrow /></a></div></section>
  <section className="section wrap" id="services"><p className="eyebrow">Services</p><h2>What I Can Help With</h2><div className="service-grid">{services.map(([title, description], index) => <article className="service-card" key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
  <section className="section projects-section" id="projects"><div className="wrap"><p className="eyebrow">Selected work</p><h2>Featured Projects</h2><p className="section-intro">Three practical Python projects built around repeatable workflows, clear outputs, and testable results.</p></div><div className="project-list">{projects.map((project, index) => <article className={`project project-${index + 1}`} key={project.title}><div className="project-image"><Image src={project.image} alt={project.alt} fill sizes="(max-width: 800px) 100vw, 48vw" /></div><div className="project-copy"><p className="project-number">0{index + 1} / 03</p><p className="role">{project.role}</p><h3>{project.title}</h3><p>{project.description}</p>{project.supporting && <p className="supporting">{project.supporting}</p>}<ul>{project.features.map((feature) => <li key={feature}>{feature}</li>)}</ul><div className="tags">{project.tech.map((tech) => <span key={tech}>{tech}</span>)}</div><a className="project-link" href={project.repository} target="_blank" rel="noreferrer">View on GitHub <Arrow /></a></div></article>)}</div></section>
  <section className="section wrap" id="stack"><p className="eyebrow">Tech stack</p><h2>Tools I Work With</h2><div className="stack-grid">{Object.entries(stack).map(([group, tools]) => <article key={group}><h3>{group}</h3><p>{tools.join(" · ")}</p></article>)}</div></section>
  <section className="section about wrap" id="about"><p className="eyebrow">About</p><div><h2>Clear workflows.<br />Practical tools.</h2><div className="about-copy"><p>I help businesses automate repetitive work, process data, connect APIs, and build practical Python tools.</p><p>I focus on projects where the result can be clearly tested and verified, including automation scripts, spreadsheet workflows, API integrations, data extraction, and small backend utilities.</p><p>I prefer practical solutions that are reliable, easy to understand, and simple to maintain.</p></div></div></section>
  <section className="section wrap credentials"><div><p className="eyebrow">Education</p><h3>Phenikaa University</h3><p>Mechatronics Engineering<br />2024–2027 expected</p></div><div><p className="eyebrow">Languages</p><p><strong>Vietnamese</strong><br />Native or Bilingual</p><p><strong>English</strong><br />Conversational</p></div></section>
  <section className="contact" id="contact"><div className="wrap"><p className="eyebrow">Let&apos;s talk</p><h2>Have a Workflow You Want to Automate?</h2><p>If you have repetitive data work, an existing Python script that needs improvement, an API workflow, or structured public data that needs to be collected and processed, feel free to reach out.</p><div className="actions"><a className="button primary" href={upwork} target="_blank" rel="noreferrer">Upwork <Arrow /></a><a className="button" href={github} target="_blank" rel="noreferrer">GitHub <Arrow /></a></div></div></section>
  <footer className="wrap"><div><strong>Anh N.</strong><span>Python Developer</span></div><a href={github} target="_blank" rel="noreferrer">GitHub <Arrow /></a><span>© {new Date().getFullYear()}</span></footer>
</main>; }
